### ISSUE TITLE
jandan_image_previewer.user.js 煎蛋图片预览脚本有点问题。

### ISSUE THREAD

**Issue by lonycc** [kxxoling/monkey_scripts#5]
蛋友你好，这个脚本有几个问题存在，具体如下：

- 1、点击“手贱一回”也会触发；

- 2、有的图片莫名加载慢，半天加载不出来；若是禁用脚本秒开。

**Comment by kxxoling** [comment]
1. 从来没手贱过所以没注意到这个问题。
2. 本地没遇到过，是否是首次使用脚本才会出现这样的问题？这个插件使用了 3 个远程文件，没有代理的话国内访问可能会比较缓慢，之后因为浏览器的缓存策略应该会快很多。

**Comment by lonycc** [comment]
你试下就知道了，这行`$('.commentlist .row .text a').fancybox(config);`覆盖到了“手贱一下”的情况。

**Comment by lonycc** [comment]
至于问题2，测试过，并非首次加载的问题，我觉得是图片太大导致。另，预览功能对长图效果很差，不如直接查看原图。

**Comment by lonycc** [comment]
建议`$('.commentlist .row .text a').fancybox(config);`改成`$('a:contains("[查看原图]")').fancybox(config);`

**Comment by kxxoling** [comment]
> 你试下就知道了，这行$('.commentlist .row .text a').fancybox(config);覆盖到了“手贱一下”的情况。

> 建议$('.commentlist .row .text a').fancybox(config);改成$('a:contains("[查看原图]")').fancybox(config);

已经改完了，“手贱一回”跟“查看原图”的类名不一样，不用这么麻烦。

**Comment by lonycc** [comment]
按我的改法，在首页右侧栏点击查看原图，也能预览；按你的改法则不行。
